name: Flutter Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: stable

      - name: Configure Flutter Web
        run: flutter create . --platforms web

      - name: Remove default Flutter test
        run: rm -rf test

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kurddesign-ai-web
          path: build/web
